//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamMgmtCal.Core.Email.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamMgmtCal.Core.Email.Templates.EmailTemplates", typeof(EmailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;#TEAMNAME#&lt;/h1&gt;
        ///&lt;h2&gt;The Following Agents Are Off Today&lt;/h2&gt;
        ///&lt;ul&gt;
        ///    #AGENTSOFFTODAY#
        ///&lt;/ul&gt;
        ///&lt;br/&gt;&lt;br/&gt;
        ///&lt;h2&gt;UpComing Days Off&lt;/h2&gt;
        ///&lt;ul&gt;
        ///    #UPCOMINGDAYSOFF#
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string DailyAttendanceReportTemplate {
            get {
                return ResourceManager.GetString("DailyAttendanceReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ForgotPasswordTemplate {
            get {
                return ResourceManager.GetString("ForgotPasswordTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///	/* ********************** base classes ********************** */
        ///	body{font-family:Arial, Helvetica, sans-serif;background-color:#fff; color:#000;}
        ///	h1{font-size:1.3em; padding:5px; border-bottom:solid 1px #AAAAAA;}
        ///	.msgBody{color:black;padding:6px;margin-bottom:4px;font-size:x-small;background-color: #D9DFF0;border: #5F8EE7 1px solid; color:#000;}
        ///	.msgSig{color:black;padding:6px;margin-bottom:4px;font-size:x-small;}
        ///	
        ///	
        ///	/* ********************** ui-widget [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Body#
        ///
        ///___________
        ///#Signature#.
        /// </summary>
        internal static string Master_PlainText {
            get {
                return ResourceManager.GetString("Master_PlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;A New Time-Off Request Has Been Submitted&lt;/h1&gt;
        ///&lt;p&gt;A Time-Of Request has been submitted for approvial.&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;Requested By : &lt;b&gt;#REQBY#&lt;/b&gt;&lt;/li&gt;
        ///    &lt;li&gt;Request Type : &lt;b&gt;#REQTYPE#&lt;/b&gt;&lt;/li&gt;
        ///    &lt;li&gt;Start Date : #STARTDATE#&lt;/li&gt;
        ///    &lt;li&gt;End Date : #ENDDATE#&lt;/li&gt;
        ///    &lt;li&gt;Hours : #HOURS#&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;hr/&gt;
        ///&lt;p&gt;#REQNOTES#&lt;/p&gt;.
        /// </summary>
        internal static string NewRequestTemplate {
            get {
                return ResourceManager.GetString("NewRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;New User Account Information&lt;/h1&gt;
        ///&lt;p&gt;A new account has been created for you to use with the team management calendar.&lt;/p&gt;
        ///&lt;p&gt;You can access your account here : #URL#&lt;/p&gt;
        ///&lt;p&gt;Using The Following Credentials:&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;Username : &lt;b&gt;#USERNAME#&lt;/b&gt;&lt;/li&gt;
        ///    &lt;li&gt;Password : &lt;b&gt;#PASSWORD#&lt;/b&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;The Following Time-Off Request Has been #RESPONSE#&lt;/h1&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;Requested By : &lt;b&gt;#REQBY#&lt;/b&gt;&lt;/li&gt;
        ///    &lt;li&gt;Request Type : &lt;b&gt;#REQTYPE#&lt;/b&gt;&lt;/li&gt;
        ///    &lt;li&gt;Start Date : #STARTDATE#&lt;/li&gt;
        ///    &lt;li&gt;End Date : #ENDDATE#&lt;/li&gt;
        ///    &lt;li&gt;Hours : #HOURS#&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;hr/&gt;
        ///&lt;p&gt;#RESPONSENOTES#&lt;/p&gt;.
        /// </summary>
        internal static string RequestResponseTemplate {
            get {
                return ResourceManager.GetString("RequestResponseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;#AGENTNAME# Has Called in Sick&lt;/h1&gt;
        ///&lt;p&gt;Please be aware that #AGENTNAME# has called in sick and will not be reporting to work for:&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;Start Date : #STARTDATE#&lt;/li&gt;
        ///    &lt;li&gt;End Date : #ENDDATE#&lt;/li&gt;
        ///    &lt;li&gt;Hours : #HOURS&lt;/li&gt;
        ///    &lt;li&gt;Reported By : #REPORTEDBY#&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;hr/&gt;
        ///#REQUESTNOTES#.
        /// </summary>
        internal static string SickNotificationTemplate {
            get {
                return ResourceManager.GetString("SickNotificationTemplate", resourceCulture);
            }
        }
    }
}
